In [31]:
import pandas as pd

In [32]:
df = pd.read_csv(
    "/content/data.csv",
    sep=";",
    encoding="latin1"
)

In [33]:
df.head()

,Group,Sex,Age,Patients number per hour,Arrival mode,Injury,Chief_complain,Mental,Pain,NRS_pain,...,BT,Saturation,KTAS_RN,Diagnosis in ED,Disposition,KTAS_expert,Error_group,Length of stay_min,KTAS duration_min,mistriage
0,2,2,71,3,3,2,right ocular pain,1,1,2,...,36.6,100,2,Corneal abrasion,1,4,2,86,"5,00",1
1,1,1,56,12,3,2,right forearm burn,1,1,2,...,36.5,NaN,4,"Burn of hand, firts degree dorsum",1,5,4,64,"3,95",1
2,2,1,68,8,2,2,"arm pain, Lt",1,1,2,...,36.6,98,4,"Fracture of surgical neck of humerus, closed",2,5,4,862,"1,00",1
3,1,2,71,8,1,1,ascites tapping,1,1,3,...,36.5,NaN,4,Alcoholic liver cirrhosis with ascites,1,5,6,108,"9,83",1
4,1,2,58,4,3,1,"distension, abd",1,1,3,...,36.5,NaN,4,Ascites,1,5,8,109,"6,60",1

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1267 entries, 0 to 1266
Data columns (total 24 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Group                     1267 non-null   int64
 1   Sex                       1267 non-null   int64
 2   Age                       1267 non-null   int64
 3   Patients number per hour  1267 non-null   int64
 4   Arrival mode              1267 non-null   int64
 5   Injury                    1267 non-null   int64
 6   Chief_complain            1267 non-null   object
 7   Mental                    1267 non-null   int64
 8   Pain                      1267 non-null   int64
 9   NRS_pain                  1267 non-null   object
 10  SBP                       1267 non-null   object
 11  DBP                       1267 non-null   object
 12  HR                        1267 non-null   object
 13  RR                        1267 non-null   object
 14  BT                        1267 non-null   object
 15  Saturation                579 non-null    object
 16  KTAS_RN                   1267 non-null   int64
 17  Diagnosis in ED           1265 non-null   object
 18  Disposition               1267 non-null   int64
 19  KTAS_expert               1267 non-null   int64
 20  Error_group               1267 non-null   int64
 21  Length of stay_min        1267 non-null   int64
 22  KTAS duration_min         1267 non-null   object
 23  mistriage                 1267 non-null   int64
dtypes: int64(14), object(10)
memory usage: 237.7+ KB

In [35]:
df.describe(include="all")

,Group,Sex,Age,Patients number per hour,Arrival mode,Injury,Chief_complain,Mental,Pain,NRS_pain,...,BT,Saturation,KTAS_RN,Diagnosis in ED,Disposition,KTAS_expert,Error_group,Length of stay_min,KTAS duration_min,mistriage
count,1267.000000,1267.000000,1267.000000,1267.000000,1267.000000,1267.000000,1267,1267.000000,1267.000000,1267,...,1267,579,1267.000000,1265,1267.000000,1267.000000,1267.000000,1267.000000,1267,1267.000000
unique,NaN,NaN,NaN,NaN,NaN,NaN,417,NaN,NaN,11,...,46,22,NaN,583,NaN,NaN,NaN,NaN,392,NaN
top,NaN,NaN,NaN,NaN,NaN,NaN,abd pain,NaN,NaN,#BOÞ!,...,36.5,98,NaN,Acute gastroenteritis,NaN,NaN,NaN,NaN,"2,00",NaN
freq,NaN,NaN,NaN,NaN,NaN,NaN,72,NaN,NaN,556,...,149,228,NaN,49,NaN,NaN,NaN,NaN,173,NaN
mean,1.456985,1.521705,54.423836,7.519337,2.820837,1.192581,NaN,1.105762,0.563536,NaN,...,NaN,NaN,3.335438,NaN,1.609313,3.265983,0.558011,11016.102605,NaN,0.250197
std,0.498343,0.499726,19.725033,3.160563,0.807904,0.394482,NaN,0.447768,0.496143,NaN,...,NaN,NaN,0.885391,NaN,1.157983,0.885803,1.571489,80446.092065,NaN,0.628250
min,1.000000,1.000000,16.000000,1.000000,1.000000,1.000000,NaN,1.000000,0.000000,NaN,...,NaN,NaN,1.000000,NaN,1.000000,1.000000,0.000000,0.000000,NaN,0.000000
25%,1.000000,1.000000,37.000000,5.000000,2.000000,1.000000,NaN,1.000000,0.000000,NaN,...,NaN,NaN,3.000000,NaN,1.000000,3.000000,0.000000,133.000000,NaN,0.000000
50%,1.000000,2.000000,57.000000,7.000000,3.000000,1.000000,NaN,1.000000,1.000000,NaN,...,NaN,NaN,3.000000,NaN,1.000000,3.000000,0.000000,274.000000,NaN,0.000000
75%,2.000000,2.000000,71.000000,10.000000,3.000000,1.000000,NaN,1.000000,1.000000,NaN,...,NaN,NaN,4.000000,NaN,2.000000,4.000000,0.000000,606.500000,NaN,0.000000
max,2.000000,2.000000,96.000000,17.000000,7.000000,2.000000,NaN,4.000000,1.000000,NaN,...,NaN,NaN,5.000000,NaN,7.000000,5.000000,9.000000,709510.000000,NaN,2.000000

In [36]:
df.isnull().sum()# which column have null value

Group                         0
Sex                           0
Age                           0
Patients number per hour      0
Arrival mode                  0
Injury                        0
Chief_complain                0
Mental                        0
Pain                          0
NRS_pain                      0
SBP                           0
DBP                           0
HR                            0
RR                            0
BT                            0
Saturation                  688
KTAS_RN                       0
Diagnosis in ED               2
Disposition                   0
KTAS_expert                   0
Error_group                   0
Length of stay_min            0
KTAS duration_min             0
mistriage                     0
dtype: int64

In [37]:
df["KTAS_expert"].value_counts()

KTAS_expert
3    487
4    459
2    220
5     75
1     26
Name: count, dtype: int64

In [38]:
df["Chief_complain"].value_counts().head(20)

Chief_complain
abd pain            72
dyspnea             60
dizziness           59
fever               45
ant. chest pain     44
Open Wound          31
headache            30
mental change       22
epigastric pain     22
general weakness    21
pain, chest         16
vomiting            16
hematemesis         14
Abd. pain           12
Left chest pain     12
Lt flank pain       11
abdomen pain        10
dysarthria          10
syncope             10
facial injury        9
Name: count, dtype: int64

In [39]:
print(df["SBP"].unique()[:20])

['160' '137' '130' '139' '91' '140' '110' '169' '148' '141' '120' '121'
 '135' '100' '133' '124' '118' '80' '180' '125']

In [40]:
print(df["DBP"].unique()[:20])

['100' '75' '80' '94' '67' '90' '70' '86' '104' '81' '78' '82' '76' '60'
 '93' '62' '66' '72' '79' '50']

In [41]:
print(df["HR"].unique()[:20])

['84' '60' '102' '88' '93' '94' '70' '80' '91' '72' '86' '106' '85' '100'
 '90' '109' '68' '125' '76' '98']

In [42]:
print(df["RR"].unique()[:20])

['18' '20' '16' '22' '??' '28' '26' '30' '24' '23' '14']

In [43]:
print(df["BT"].unique()[:20])

['36.6' '36.5' '38.1' '36.2' '36' '36.3' '36.4' '37.6' '36.0' '37.4' '37'
 '37.1' '36.8' '36.1' '36.7' '36.9' '37.2' '38' '38.3' '37.5']

In [44]:
print(df["KTAS duration_min"].unique()[:20])

['5,00' '3,95' '1,00' '9,83' '6,60' '2,00' '3,00' '10,23' '3,23' '4,00'
 '7,53' '7,15' '8,00' '9,88' '10,53' '12,45' '9,48' '5,50' '8,78' '8,17']

In [45]:
import numpy as np

In [46]:
df_clean = df.copy()#copy of dataset

In [47]:
df_clean["RR"] = df_clean["RR"].replace("??", np.nan)#fix null value

In [48]:
numeric_columns = [
    "SBP",
    "DBP",
    "HR",
    "RR",
    "BT"
]

for col in numeric_columns:
    df_clean[col] = pd.to_numeric(df_clean[col], errors="coerce")

In [49]:
df_clean["KTAS duration_min"] = (
    df_clean["KTAS duration_min"]
    .str.replace(",", ".", regex=False)
)

In [50]:
df_clean["KTAS duration_min"] = pd.to_numeric(
    df_clean["KTAS duration_min"],
    errors="coerce"
)

In [51]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1267 entries, 0 to 1266
Data columns (total 24 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Group                     1267 non-null   int64
 1   Sex                       1267 non-null   int64
 2   Age                       1267 non-null   int64
 3   Patients number per hour  1267 non-null   int64
 4   Arrival mode              1267 non-null   int64
 5   Injury                    1267 non-null   int64
 6   Chief_complain            1267 non-null   object
 7   Mental                    1267 non-null   int64
 8   Pain                      1267 non-null   int64
 9   NRS_pain                  1267 non-null   object
 10  SBP                       1242 non-null   float64
 11  DBP                       1238 non-null   float64
 12  HR                        1247 non-null   float64
 13  RR                        1245 non-null   float64
 14  BT                        1249 non-null   float64
 15  Saturation                579 non-null    object
 16  KTAS_RN                   1267 non-null   int64
 17  Diagnosis in ED           1265 non-null   object
 18  Disposition               1267 non-null   int64
 19  KTAS_expert               1267 non-null   int64
 20  Error_group               1267 non-null   int64
 21  Length of stay_min        1267 non-null   int64
 22  KTAS duration_min         1267 non-null   float64
 23  mistriage                 1267 non-null   int64
dtypes: float64(6), int64(14), object(4)
memory usage: 237.7+ KB

In [52]:
columns_to_drop = [
    "Diagnosis in ED",
    "Disposition",
    "KTAS_RN",
    "Error_group",
    "Length of stay_min",
    "KTAS duration_min",
    "mistriage"
]

df_clean = df_clean.drop(columns=columns_to_drop)

In [53]:
df_clean.columns

Index(['Group', 'Sex', 'Age', 'Patients number per hour', 'Arrival mode',
       'Injury', 'Chief_complain', 'Mental', 'Pain', 'NRS_pain', 'SBP', 'DBP',
       'HR', 'RR', 'BT', 'Saturation', 'KTAS_expert'],
      dtype='object')

In [54]:
print(df_clean["Group"].value_counts())

Group
1    688
2    579
Name: count, dtype: int64

In [55]:
print(df_clean.groupby("Group")["KTAS_expert"].value_counts())

Group  KTAS_expert
1      4              276
       3              270
       2               72
       5               56
       1               14
2      3              217
       4              183
       2              148
       5               19
       1               12
Name: count, dtype: int64

In [56]:
df_clean.isnull().sum()

Group                         0
Sex                           0
Age                           0
Patients number per hour      0
Arrival mode                  0
Injury                        0
Chief_complain                0
Mental                        0
Pain                          0
NRS_pain                      0
SBP                          25
DBP                          29
HR                           20
RR                           22
BT                           18
Saturation                  688
KTAS_expert                   0
dtype: int64

In [57]:
numeric_cols = ["SBP", "DBP", "HR", "RR", "BT"]

for col in numeric_cols:
    df_clean[col] = df_clean[col].fillna(df_clean[col].median())

In [58]:
df_clean["Saturation_missing"] = df_clean["Saturation"].isnull().astype(int)

In [59]:
df_clean["Saturation"] = pd.to_numeric(df_clean["Saturation"], errors="coerce")
df_clean["Saturation"] = df_clean["Saturation"].fillna(df_clean["Saturation"].median())

In [60]:
df_clean.isnull().sum()

Group                       0
Sex                         0
Age                         0
Patients number per hour    0
Arrival mode                0
Injury                      0
Chief_complain              0
Mental                      0
Pain                        0
NRS_pain                    0
SBP                         0
DBP                         0
HR                          0
RR                          0
BT                          0
Saturation                  0
KTAS_expert                 0
Saturation_missing          0
dtype: int64

Separate Features (X) and Target (y)

In [61]:
y = df_clean["KTAS_expert"]

In [62]:
X = df_clean.drop(columns=["KTAS_expert"])

In [63]:
print(df_clean["NRS_pain"].value_counts())#inspecting nrs pain

NRS_pain
#BOÞ!    556
3        278
4        141
5        136
6         70
2         38
7         33
8          9
10         3
1          2
9          1
Name: count, dtype: int64

In [64]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [65]:
# X contains everything the AI can see
X = df_clean.drop(columns=["KTAS_expert"])

# y contains the correct answer
y = df_clean["KTAS_expert"]

In [66]:
print(X.shape)
print(y.shape)

(1267, 17)
(1267,)

In [67]:
print(X.dtypes)#to check what isnt number

Group                         int64
Sex                           int64
Age                           int64
Patients number per hour      int64
Arrival mode                  int64
Injury                        int64
Chief_complain               object
Mental                        int64
Pain                          int64
NRS_pain                     object
SBP                         float64
DBP                         float64
HR                          float64
RR                          float64
BT                          float64
Saturation                  float64
Saturation_missing            int64
dtype: object

In [68]:
print(df_clean["NRS_pain"].value_counts())

NRS_pain
#BOÞ!    556
3        278
4        141
5        136
6         70
2         38
7         33
8          9
10         3
1          2
9          1
Name: count, dtype: int64

In [69]:
print(df_clean["Chief_complain"].nunique())

417

In [70]:
print(df_clean["Chief_complain"].sample(20, random_state=42))

1211                 Open Wound
1039                     arrest
422                     dyspnea
1119                      fever
848                Near syncope
781         for ascites tapping
23      Rt. side motor weakness
405                     dyspnea
43                  throat pain
581               foot swelling
1176                 Convulsion
552                    abd pain
1072                    dyspnea
308        upper abdominal pain
382                 head trauma
1164                      fever
490                   toothache
78                leg pain left
609                  Open Wound
1208    Hyperkalemia (disorder)
Name: Chief_complain, dtype: object

In [71]:
# Replace the invalid value with NaN
df_clean["NRS_pain"] = df_clean["NRS_pain"].replace("#BOÞ!", np.nan)

# Convert to numeric
df_clean["NRS_pain"] = pd.to_numeric(df_clean["NRS_pain"], errors="coerce")

# Fill missing values with the median pain score
df_clean["NRS_pain"] = df_clean["NRS_pain"].fillna(df_clean["NRS_pain"].median())

In [72]:
df_clean["Chief_complain"] = (
    df_clean["Chief_complain"]
    .str.lower()      # Convert everything to lowercase
    .str.strip()      # Remove extra spaces
)

In [73]:
print(df_clean["Chief_complain"].sample(20, random_state=42))

1211                 open wound
1039                     arrest
422                     dyspnea
1119                      fever
848                near syncope
781         for ascites tapping
23      rt. side motor weakness
405                     dyspnea
43                  throat pain
581               foot swelling
1176                 convulsion
552                    abd pain
1072                    dyspnea
308        upper abdominal pain
382                 head trauma
1164                      fever
490                   toothache
78                leg pain left
609                  open wound
1208    hyperkalemia (disorder)
Name: Chief_complain, dtype: object

In [74]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier

In [75]:
text_feature = "Chief_complain"

numeric_features = [
    "Sex",
    "Age",
    "Arrival mode",
    "Injury",
    "Mental",
    "Pain",
    "NRS_pain",
    "SBP",
    "DBP",
    "HR",
    "RR",
    "BT",
    "Saturation",
    "Saturation_missing"
]

In [76]:
numeric_transformer = Pipeline([
    ("imputer", SimpleImputer(strategy="median"))
])#missing values int will be filled by median

In [77]:
text_transformer = Pipeline([
    ("tfidf", TfidfVectorizer(max_features=100))
])#converting text data

In [78]:
preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numeric_features),
        ("text", text_transformer, text_feature)
    ]
)

In [79]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)#spliting dataset into training and testing

In [80]:
model = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", RandomForestClassifier(
        n_estimators=200,
        random_state=42
    ))
])

In [81]:
model.fit(X_train, y_train)

ValueError: Cannot use median strategy with non-numeric data:
could not convert string to float: '#BOÞ!'

In [82]:
print(df_clean["NRS_pain"].dtype)
print(df_clean["NRS_pain"].head())

float64
0    2.0
1    2.0
2    2.0
3    3.0
4    3.0
Name: NRS_pain, dtype: float64

In [83]:
X = df_clean.drop(columns=["KTAS_expert"])
y = df_clean["KTAS_expert"]

In [84]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [85]:
model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median'))]),
                                                  ['Sex', 'Age', 'Arrival mode',
                                                   'Injury', 'Mental', 'Pain',
                                                   'NRS_pain', 'SBP', 'DBP',
                                                   'HR', 'RR', 'BT',
                                                   'Saturation',
                                                   'Saturation_missing']),
                                                 ('text',
                                                  Pipeline(steps=[('tfidf',
                                                                   TfidfVectorizer(max_features=100))]),
                                                  'Chief_complain')])),
                ('classifier',
                 RandomForestClassifier(n_estimators=200, random_state=42))])

In [86]:
y_pred = model.predict(X_test)

metrices

In [87]:
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

In [88]:
accuracy = accuracy_score(y_test, y_pred)

print(f"Accuracy: {accuracy:.4f}")

Accuracy: 0.7244

In [90]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       1.00      0.40      0.57         5
           2       0.66      0.57      0.61        44
           3       0.71      0.80      0.75        98
           4       0.76      0.85      0.80        92
           5       1.00      0.07      0.12        15

    accuracy                           0.72       254
   macro avg       0.82      0.54      0.57       254
weighted avg       0.74      0.72      0.70       254

In [89]:
cm = confusion_matrix(y_test, y_pred)

print(cm)

[[ 2  2  1  0  0]
 [ 0 25 13  6  0]
 [ 0  7 78 13  0]
 [ 0  4 10 78  0]
 [ 0  0  8  6  1]]

In [91]:
import joblib

joblib.dump(model, "triage_model.joblib")

['triage_model.joblib']